language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - phpenv rehash
  - curl http://install.onionphp.org/ | bash
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - composer install --dev

script:
  - source phpbrew.sh
  - php bin/phpbrew
  - php bin/phpbrew known
  - phpunit --debug
# notifications:
#  webbooks: http://wireroom.extremedev.org/=/travis-ci/Hall
